"use client";

import { createContext, useContext, useState, ReactNode, useMemo, FC } from 'react';

export type Language = 'en' | 'de' | 'fr' | 'it' | 'es' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Record<string, string>;
  availableLanguages: {key: Language, name: string}[];
}

const translationsDb: Record<Language, Record<string, string>> = {
  en: {
    welcome: "How can I help you today?",
    placeholder: "Ask something about your finances...",
    signOut: "Sign Out",
    newChat: "New Chat",
    rename: "Rename",
    delete: "Delete",
    clearChatTitle: "Delete Thread",
    clearChatConfirmTitle: "Are you sure?",
    clearChatConfirmDescription: "This will permanently delete this chat thread and all of its messages. This action cannot be undone.",
    clearChatConfirmAction: "Yes, delete it",
    loginTitle: "Welcome Back",
    loginDescription: "Sign in to access your financial advisor",
    emailLabel: "Email",
    passwordLabel: "Password",
    signInButton: "Sign In",
    loginNoAccount: "Don't have an account?",
    signUpLink: "Sign up",
    loginFailed: "Login Failed",
    signUpTitle: "Create an Account",
    signUpDescription: "Start your journey to financial wellness",
    signUpButton: "Sign Up",
    signUpHaveAccount: "Already have an account?",
    signInLink: "Sign in",
    signUpFailed: "Sign Up Failed",
    language: "Language",
    chatTitle: "Recent",
    financialOverview: "Financial Overview",
    profileTitle: "Your Financial Profile",
    profileSubtitle: "Monthly income and capital",
    riskTitle: "Risk Profile",
    riskSubtitle: "Based on your answers",
    goalsTitle: "Financial Goals",
    goalsSubtitle: "Your primary objectives",
    insightsTitle: "Insights",
    insightsContent: "AI-powered suggestions will appear here.",
    parse_error: "I'm sorry, I didn't quite understand that. Could you please provide the information again?",
    parse_error_final: "I'm sorry, I wasn't able to gather all the required information. Let's try that last question again.",
    api_error: "I'm having trouble connecting to my services right now. Please try again in a moment.",
  },
  de: {
    welcome: "Wie kann ich Ihnen heute helfen?",
    placeholder: "Fragen Sie etwas über Ihre Finanzen...",
    signOut: "Abmelden",
    newChat: "Neuer Chat",
    rename: "Umbenennen",
    delete: "Löschen",
    clearChatTitle: "Thread löschen",
    clearChatConfirmTitle: "Sind Sie sicher?",
    clearChatConfirmDescription: "Dadurch wird dieser Chat-Thread und alle seine Nachrichten dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
    clearChatConfirmAction: "Ja, löschen",
    loginTitle: "Willkommen zurück",
    loginDescription: "Melden Sie sich an, um auf Ihren Finanzberater zuzugreifen",
    emailLabel: "E-Mail",
    passwordLabel: "Passwort",
    signInButton: "Anmelden",
    loginNoAccount: "Haben Sie noch kein Konto?",
    signUpLink: "Registrieren",
    loginFailed: "Anmeldung fehlgeschlagen",
    signUpTitle: "Konto erstellen",
    signUpDescription: "Beginnen Sie Ihre Reise zum finanziellen Wohlbefinden",
    signUpButton: "Registrieren",
    signUpHaveAccount: "Haben Sie bereits ein Konto?",
    signInLink: "Anmelden",
    signUpFailed: "Registrierung fehlgeschlagen",
    language: "Sprache",
    chatTitle: "Letzte",
    financialOverview: "Finanzübersicht",
    profileTitle: "Ihr Finanzprofil",
    profileSubtitle: "Monatliches Einkommen und Kapital",
    riskTitle: "Risikoprofil",
    riskSubtitle: "Basierend auf Ihren Antworten",
    goalsTitle: "Finanzielle Ziele",
    goalsSubtitle: "Ihre primären Ziele",
    insightsTitle: "Einblicke",
    insightsContent: "KI-gestützte Vorschläge werden hier erscheinen.",
    parse_error: "Entschuldigung, das habe ich nicht ganz verstanden. Könnten Sie die Informationen bitte noch einmal angeben?",
    parse_error_final: "Entschuldigung, ich konnte nicht alle erforderlichen Informationen sammeln. Versuchen wir die letzte Frage noch einmal.",
    api_error: "Ich habe im Moment Probleme, mich mit meinen Diensten zu verbinden. Bitte versuchen Sie es in einem Moment erneut.",
  },
  fr: {
    welcome: "Comment puis-je vous aider aujourd'hui ?",
    placeholder: "Demandez quelque chose sur vos finances...",
    signOut: "Se déconnecter",
    newChat: "Nouveau chat",
    rename: "Renommer",
    delete: "Supprimer",
    clearChatTitle: "Supprimer le fil",
    clearChatConfirmTitle: "Êtes-vous sûr ?",
    clearChatConfirmDescription: "Cela supprimera définitivement ce fil de discussion et tous ses messages. Cette action ne peut pas être annulée.",
    clearChatConfirmAction: "Oui, supprimer",
    loginTitle: "Content de vous revoir",
    loginDescription: "Connectez-vous pour accéder à votre conseiller financier",
    emailLabel: "E-mail",
    passwordLabel: "Mot de passe",
    signInButton: "Se connecter",
    loginNoAccount: "Vous n'avez pas de compte ?",
    signUpLink: "S'inscrire",
    loginFailed: "Échec de la connexion",
    signUpTitle: "Créer un compte",
    signUpDescription: "Commencez votre voyage vers le bien-être financier",
    signUpButton: "S'inscrire",
    signUpHaveAccount: "Vous avez déjà un compte ?",
    signInLink: "Se connecter",
    signUpFailed: "Échec de l'inscription",
    language: "Langue",
    chatTitle: "Récents",
    financialOverview: "Aperçu financier",
    profileTitle: "Votre profil financier",
    profileSubtitle: "Revenu mensuel et capital",
    riskTitle: "Profil de risque",
    riskSubtitle: "Basé sur vos réponses",
    goalsTitle: "Objectifs financiers",
    goalsSubtitle: "Vos objectifs principaux",
    insightsTitle: "Aperçus",
    insightsContent: "Les suggestions basées sur l'IA apparaîtront ici.",
    parse_error: "Je suis désolé, je n'ai pas bien compris. Pourriez-vous s'il vous plaît fournir à nouveau l'information ?",
    parse_error_final: "Désolé, je n'ai pas pu rassembler toutes les informations requises. Réessayons cette dernière question.",
    api_error: "J'ai des difficultés à me connecter à mes services en ce moment. Veuillez réessayer dans un instant.",
  },
  it: {
    welcome: "Come posso aiutarti oggi?",
    placeholder: "Chiedi qualcosa sulle tue finanze...",
    signOut: "Esci",
    newChat: "Nuova chat",
    rename: "Rinomina",
    delete: "Elimina",
    clearChatTitle: "Elimina thread",
    clearChatConfirmTitle: "Sei sicuro?",
    clearChatConfirmDescription: "Questo eliminerà permanentemente questo thread di chat e tutti i suoi messaggi. Questa azione non può essere annullata.",
    clearChatConfirmAction: "Sì, elimina",
    loginTitle: "Bentornato",
    loginDescription: "Accedi per consultare il tuo consulente finanziario",
    emailLabel: "E-mail",
    passwordLabel: "Password",
    signInButton: "Accedi",
    loginNoAccount: "Non hai un account?",
    signUpLink: "Iscriviti",
    loginFailed: "Accesso fallito",
    signUpTitle: "Crea un account",
    signUpDescription: "Inizia il tuo viaggio verso il benessere finanziario",
    signUpButton: "Iscriviti",
    signUpHaveAccount: "Hai già un account?",
    signInLink: "Accedi",
    signUpFailed: "Registrazione fallita",
    language: "Lingua",
    chatTitle: "Recenti",
    financialOverview: "Panoramica finanziaria",
    profileTitle: "Il tuo profilo finanziario",
    profileSubtitle: "Reddito mensile e capitale",
    riskTitle: "Profilo di rischio",
    riskSubtitle: "In base alle tue risposte",
    goalsTitle: "Obiettivi finanziari",
    goalsSubtitle: "I tuoi obiettivi principali",
    insightsTitle: "Approfondimenti",
    insightsContent: "I suggerimenti basati sull'IA appariranno qui.",
    parse_error: "Mi dispiace, non ho capito bene. Potresti fornire di nuovo l'informazione?",
    parse_error_final: "Mi dispiace, non sono riuscito a raccogliere tutte le informazioni richieste. Riprova con l'ultima domanda.",
    api_error: "Al momento ho problemi di connessione ai miei servizi. Riprova tra un istante.",
  },
  es: {
    welcome: "¿Cómo puedo ayudarte hoy?",
    placeholder: "Pregunta algo sobre tus finanzas...",
    signOut: "Cerrar sesión",
    newChat: "Nuevo Chat",
    rename: "Renombrar",
    delete: "Eliminar",
    clearChatTitle: "Eliminar Hilo",
    clearChatConfirmTitle: "¿Estás seguro?",
    clearChatConfirmDescription: "Esto eliminará permanentemente este hilo de chat y todos sus mensajes. Esta acción no se puede deshacer.",
    clearChatConfirmAction: "Sí, eliminar",
    loginTitle: "Bienvenido de Nuevo",
    loginDescription: "Inicia sesión para acceder a tu asesor financiero",
    emailLabel: "Correo electrónico",
    passwordLabel: "Contraseña",
    signInButton: "Iniciar Sesión",
    loginNoAccount: "¿No tienes una cuenta?",
    signUpLink: "Regístrate",
    loginFailed: "Error de inicio de sesión",
    signUpTitle: "Crear una Cuenta",
    signUpDescription: "Comienza tu viaje hacia el bienestar financiero",
    signUpButton: "Registrarse",
    signUpHaveAccount: "¿Ya tienes una cuenta?",
    signInLink: "Iniciar sesión",
    signUpFailed: "Error de registro",
    language: "Idioma",
    chatTitle: "Recientes",
    financialOverview: "Resumen financiero",
    profileTitle: "Tu perfil financiero",
    profileSubtitle: "Ingresos mensuales y capital",
    riskTitle: "Perfil de riesgo",
    riskSubtitle: "Basado en tus respuestas",
    goalsTitle: "Metas financieras",
    goalsSubtitle: "Tus objetivos principales",
    insightsTitle: "Perspectivas",
    insightsContent: "Las sugerencias de IA aparecerán aquí.",
  },
  zh: {
    welcome: "今天我能如何帮助您？",
    placeholder: "询问有关您财务的任何问题...",
    signOut: "登出",
    newChat: "新聊天",
    rename: "重命名",
    delete: "删除",
    clearChatTitle: "删除对话",
    clearChatConfirmTitle: "您确定吗？",
    clearChatConfirmDescription: "这将永久删除此聊天对话及其所有消息。此操作无法撤销。",
    clearChatConfirmAction: "是的，删除",
    loginTitle: "欢迎回来",
    loginDescription: "登录以访问您的财务顾问",
    emailLabel: "电子邮件",
    passwordLabel: "密码",
    signInButton: "登录",
    loginNoAccount: "还没有帐户？",
    signUpLink: "注册",
    loginFailed: "登录失败",
    signUpTitle: "创建帐户",
    signUpDescription: "开启您的财务健康之旅",
    signUpButton: "注册",
    signUpHaveAccount: "已有帐户？",
    signInLink: "登录",
    signUpFailed: "注册失败",
    language: "语言",
    chatTitle: "最近",
    financialOverview: "财务概览",
    profileTitle: "您的财务状况",
    profileSubtitle: "月收入和资本",
    riskTitle: "风险状况",
    riskSubtitle: "根据您的回答",
    goalsTitle: "财务目标",
    goalsSubtitle: "您的主要目标",
    insightsTitle: "见解",
    insightsContent: "人工智能建议将显示在此处。",
  },
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  
  const value = useMemo(() => ({
    language,
    setLanguage: (lang: Language) => setLanguage(lang),
    translations: translationsDb[language],
    availableLanguages: [
        { key: 'en', name: 'English' },
        { key: 'de', name: 'Deutsch' },
        { key: 'fr', name: 'Français' },
        { key: 'it', name: 'Italiano' },
        { key: 'es', name: 'Español' },
        { key: 'zh', name: '中文' },
    ],
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

    